#dubbo相关的配置
dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: gmall-admin-web
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
  # scan: com.mdh.gmall.pms.service.impl  #服务暴露与发现消费所在的package
  consumer:
    check: false #关闭启动检查

server:
  port: 8081

gmall:
  jwt:
    tokenHeader: Authorization
    secret: atguigu_2019
    expiration: 604800
    tokenHead: Bearer


#在web项目中是不需要数据源的
#但是在GmallAdminWebApplication上注解没生效？  待解决
#  @SpringBootApplication(exclude = {
#        DataSourceAutoConfiguration.class,
#        DataSourceTransactionManagerAutoConfiguration.class,
#        HibernateJpaAutoConfiguration.class})
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver