
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localho47.100.77.124:3306/gmall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver